version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
  web:
    restart: always
    build: ./web
    ports:
      - 8000:80
    volumes:
      - app:/usr/src/app
      - static:/usr/src/app/static
    env_file: web/pyproject.toml
    environment:
      DEBUG: 'true'
    command: poetry run gunicorn -w 4 -b 0.0.0.0:8000 "main_app:create_app()"

volumes:
  app:
  static:
  web-static: